services:

  postgres:
    image: postgres:16.1
    container_name: portfolio_postgres
    restart: always
    environment:
      POSTGRES_USER: ${PORTFOLIO_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_passwd
      POSTGRES_DB: ${PORTFOLIO_POSTGRES_DB:-postgres}
    ports:
      - ${PORTFOLIO_POSTGRES_PORT:-5432}:5432
    healthcheck:
      test: pg_isready -U ${PORTFOLIO_POSTGRES_USER:-postgres} -d ${PORTFOLIO_POSTGRES_DB:-postgres}
      interval: 5s
    secrets:
      - pg_passwd
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: portfolio_redis
    restart: always
    command: redis-server /etc/redis/redis.conf
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_passwd
    ports:
      - ${PORTFOLIO_REDIS_PORT:-6379}:6379
    secrets:
      - redis_passwd
    volumes:
      - ./docker/local/redis:/etc/redis
      - redis_data:/data
    entrypoint: /etc/redis/entrypoint.sh

volumes:
  pg_data:
    name: portfolio_pg
  redis_data:
    name: portfolio_redis

secrets:
  pg_passwd:
    environment: PORTFOLIO_POSTGRES_PASSWORD
  redis_passwd:
    environment: PORTFOLIO_REDIS_PASSWORD
