# Generated by Django 2.1.3 on 2018-11-11 16:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=128)),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Navbar title')),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=256, verbose_name='SEO keywords')),
                ('seo_description', models.CharField(blank=True, default='', max_length=512, verbose_name='SEO description')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('google_plus_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', help_text='The contact email to display in footer.', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=128)),
                ('email_form', models.EmailField(blank=True, default='', help_text='The email to send form submission.', max_length=254)),
                ('timetable', wagtail.core.fields.RichTextField(blank=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'db_table': 'portfolio_settings',
            },
        ),
    ]
