# Generated by Django 2.1.3 on 2018-11-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Google Analytics ID'),
        ),
    ]
