# Generated by Django 2.1.3 on 2018-11-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosettings',
            name='email',
            field=models.EmailField(blank=True, default='', help_text="L'adresse email affiché en pied de page.", max_length=254),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='email_form',
            field=models.EmailField(blank=True, default='', help_text="L'adresse email de contact du formulaire.", max_length=254),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='navbar_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titre menu'),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='seo_description',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Description SEO'),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Mots clés SEO'),
        ),
    ]
