# Generated by Django 2.1.3 on 2018-11-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('core', '0002_portfoliosettings_google_analytics_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosettings',
            name='lb_brand',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='lb_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Local Business Image'),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='lb_opening_hours',
            field=models.CharField(blank=True, default='', help_text='Exemple: Mo,Tu,We,Th,Fr,Sa 10:00-20:30', max_length=128, verbose_name='Horaires'),
        ),
        migrations.AddField(
            model_name='portfoliosettings',
            name='lb_polygon',
            field=models.CharField(blank=True, default='', help_text='Au format polygone. Outil: https://www.doogal.co.uk/polylines.php. Exemple: -1.4585973651364839,47.24680912120602,0 -1.4531042010739839,47.24121534312366,0 -1.3267614276364839,47.83271445708654,0 -1.9969274432614839,47.86404914329155,0 -1.9831945331052339,47.29153808284894,0 -1.4585973651364839,47.24680912120602,0', max_length=512, verbose_name='Zone de couverture'),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Google Analytics ID'),
        ),
        migrations.AlterField(
            model_name='portfoliosettings',
            name='navbar_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titre menu'),
        ),
    ]
