# Generated by Django 5.0.6 on 2024-06-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_contactformsubmission_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliosettings",
            name="favicon",
            field=models.ImageField(blank=True, default="", upload_to="icons"),
        ),
        migrations.AddField(
            model_name="portfoliosettings",
            name="logo",
            field=models.ImageField(blank=True, default="", upload_to="icons"),
        ),
    ]
