# Generated by Django 2.1.3 on 2018-11-14 22:11

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': "Page d'accueil"},
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='header_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='projects',
            field=wagtail.core.fields.StreamField([('description', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('project', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=128)), ('heading', wagtail.core.blocks.CharBlock(max_length=255)), ('date', wagtail.core.blocks.DateBlock(required=False)), ('text', wagtail.core.blocks.TextBlock(blank=True)), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(max_length=128)), ('description', wagtail.core.blocks.CharBlock(required=False)), ('services', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=128)), ('description', wagtail.core.blocks.TextBlock(required=False)), ('icon', wagtail.core.blocks.CharBlock(max_length=128))], template='home/blocks/service.html'))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team_members',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(max_length=128)), ('description', wagtail.core.blocks.CharBlock(max_length=255, required=False)), ('member', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('job', wagtail.core.blocks.CharBlock(required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='homepage',
            table='portfolio_homepage',
        ),
    ]
