# Generated by Django 2.1.3 on 2018-12-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181115_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='project_heading',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titre'),
        ),
    ]
