# Generated by Django 2.1.3 on 2018-11-14 22:19

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181114_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='project_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='projects',
            field=wagtail.core.fields.StreamField([('name', wagtail.core.blocks.CharBlock(max_length=128)), ('heading', wagtail.core.blocks.CharBlock(max_length=255)), ('date', wagtail.core.blocks.DateBlock(required=False)), ('text', wagtail.core.blocks.TextBlock(blank=True)), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services',
            field=wagtail.core.fields.StreamField([('service', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=128)), ('description', wagtail.core.blocks.TextBlock(required=False)), ('icon', wagtail.core.blocks.CharBlock(max_length=128))]))], blank=True, null=True),
        ),
    ]
