# Generated by Django 2.1.3 on 2018-11-14 19:03

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181114_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='team_members',
            field=wagtail.core.fields.StreamField([('member', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('job', wagtail.core.blocks.CharBlock(required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock())], icon='user'))], blank=True, null=True),
        ),
    ]
