# Generated by Django 2.1.3 on 2018-11-09 21:51

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181109_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
    ]
