# Generated by Django 2.1.3 on 2018-11-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181109_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='navbar_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Navbar title'),
        ),
    ]
