# Generated by Django 2.1.3 on 2018-11-09 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181109_1234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner',
            new_name='Header',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='banner',
            new_name='header',
        ),
    ]
