# Generated by Django 2.1.3 on 2018-11-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181112_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='project_intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='service_intro',
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='project_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='service_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Description'),
        ),
    ]
